"""empty message

Revision ID: 0aacdcaee862
Revises: 7d9c9e187240
Create Date: 2025-12-07 22:10:08.554947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aacdcaee862'
down_revision = '7d9c9e187240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary_report', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
