"""empty message

Revision ID: 324f4c9a6142
Revises: af1d2b88cdbc
Create Date: 2025-10-20 20:54:42.781295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324f4c9a6142'
down_revision = 'af1d2b88cdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('patronymic', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.String(length=255), nullable=True))
        batch_op.drop_column('fio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fio', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('nickname')
        batch_op.drop_column('patronymic')
        batch_op.drop_column('name')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
