"""empty message

Revision ID: 4ae877baecdb
Revises: 324f4c9a6142
Create Date: 2025-12-07 17:53:53.237997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae877baecdb'
down_revision = '324f4c9a6142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intensity', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('date_time')
        batch_op.drop_column('intensity')
        batch_op.drop_column('duration')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
