"""empty message

Revision ID: 7d9c9e187240
Revises: 4ae877baecdb
Create Date: 2025-12-07 22:07:52.668660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9c9e187240'
down_revision = '4ae877baecdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficaulty', sa.String(length=128), nullable=False),
    sa.Column('self_health', sa.String(length=128), server_default=sa.text('now()'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_skip', sa.Boolean(), nullable=True),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_report')
    # ### end Alembic commands ###
