"""empty message

Revision ID: 9d6d6d771fff
Revises: 03140efeca35
Create Date: 2025-10-12 20:34:01.040623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6d6d771fff'
down_revision = '03140efeca35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trainer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trainer_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trainer_id')
        batch_op.drop_column('is_trainer')

    # ### end Alembic commands ###
