"""empty message

Revision ID: be63e54135db
Revises: 8510f7168f38
Create Date: 2025-09-28 14:23:18.315341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be63e54135db'
down_revision = '8510f7168f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_password_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_password_key'), ['password'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
